name: neuro-physics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - sympy
  - mpmath
  - numpy
  - matplotlib
  - pybind11
  - scipy
  - pandas
  - pip
  - pip:
    - google-generativeai
    - openai
    - python-dotenv
